print("Please enter the following information:\n")
firstName = input("First name: ")
lastName = input("Last name: ")
email = input("Email address: ").lower()
phone = input("Phone number: ")
jobTitle = input("Job title: ").title()
id = input("ID Number: ")
hair = input("Hair color: ")
eye = input("Eye color: ")
month = input("Month started: ")
training = input("Have you completed advanced training? ")
print("\nThe ID card is: ")
print("----" * 10)
print(lastName.upper() + ", " + firstName)
print(jobTitle)
print("ID: " + id)
print("\n" + email)
print(phone + "\n")
print(f"{'Hair: ' + hair:<22} Eyes: {eye}")
print(f"{'Month: ' + month:<22} Training: {training}")
print("----" * 10)